CREATE TABLE BD_TEST.dbo.PRODUCTO (
	ID_PRODUCTO int NULL,
	NOMBRE varchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPCION varchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRECIO decimal(18,0) NULL,
	STOCK int NULL,
	ESTADO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);